name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create file
      run: cat /home/runner/work/MarvelComicsFinder/MarvelComicsFinder/app/google-services.json | base64
      
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/MarvelComicsFinder/MarvelComicsFinder/app/google-services.json

    - name: Build debug and preprod apks and run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: --stacktrace
      
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
